
host:
    loopback:
        ip: 1.1.1.3

underlay:
    local:
         asn: 5003
    neighbors:
      - interface: em3.300
        asn: 5004
        peer_ip: 10.10.5.2
        local_ip: 10.10.5.1
        vlan_id: 300
      - interface: em3.301
        asn: 5005
        peer_ip: 10.10.6.2
        local_ip: 10.10.6.1
        vlan_id: 301
