
host:
    loopback:
        ip: 10.10.139.4
    device: spine
    devicenumber: 4
    cluster: 2.2.2.2
underlay:
    local:
        asn: 5004
    neighbors:
      - interface: em3.101
        asn: 5001
        peer_ip: 10.10.2.1
        peer_loopback: 10.10.139.1
        local_ip: 10.10.2.2
        vlan_id: 101
      - interface: em3.201
        asn: 5002
        peer_ip: 10.10.4.1
        peer_loopback: 10.10.139.2
        local_ip: 10.10.4.2
        vlan_id: 201
