
host:
    loopback:
        ip: 10.10.139.1
    device: leaf
    devicenumber: 1
    cluster: dummy
underlay:
    local:
        asn: 5001
    neighbors:
      - interface: em3.100
        asn: 5003
        peer_ip: 10.10.1.2
        peer_loopback: 10.10.139.3
        local_ip: 10.10.1.1
        vlan_id: 100
